apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
      - name: vproapp
        image: nixxkos/vprofileapp:latest
        ports:
         -name: vproapp-port
          containerPort: 8090
      initContainers:
        - name: init-mydb
          image: busybox
          command: ['sh', '-c', 'until nslookup db01; do echo waiting for mydb; sleep 2; done;']
        - name: init-memecache
          image: busybox
          command: ['sh', '-c', 'until nslookup mc01; do echo waiting for mydb; sleep 2; done;']


